GET http://localhost:3000

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/suzuki

###
POST http://localhost:3000/users
Content-Type: application/json

{
	"userID": "katou",
	"password": "katou",
	"name": "加藤"
}

###
PUT http://localhost:3000/users/katou
Content-Type: application/json

{
	"password": "katouZ",
	"name": "加藤"
}